app-type: cron-python
jenkins-default-job: PYPI-TN-titus-isolate
jenkins-jobs:
- PYPI-TN-titus-isolate
jenkins-master: titus
name: titus-isolate
org: tn
python:
  test-versions:
  - "3.6"
tool-versions:
  python: "3.6"
