apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: "2019-08-13T23:23:00Z"
  generation: 1
  name: opportunistic-resources.titus.netflix.com
  resourceVersion: "472028"
  selfLink: /apis/apiextensions.k8s.io/v1beta1/customresourcedefinitions/opportunistic-resources.titus.netflix.com
  uid: 4a4afa45-be21-11e9-b347-120874de55a6
spec:
  conversion:
    strategy: None
  group: titus.netflix.com
  names:
    kind: OpportunisticResource
    listKind: OpportunisticResourceList
    plural: opportunistic-resources
    singular: opportunistic-resource
  scope: Namespaced
  version: v1
  versions:
  - name: v1
    served: true
    storage: true
status:
  acceptedNames:
    kind: OpportunisticResource
    listKind: OpportunisticResourceList
    plural: opportunistic-resources
    singular: opportunistic-resource
  conditions:
  - lastTransitionTime: "2019-08-13T23:23:00Z"
    message: no conflicts found
    reason: NoConflicts
    status: "True"
    type: NamesAccepted
  - lastTransitionTime: null
    message: the initial names have been accepted
    reason: InitialNamesAccepted
    status: "True"
    type: Established
  storedVersions:
  - v1
