steps:
  - label: Build titus-isolate debian package
    command: docker build -t deb release && docker run --rm -e TITUS_ISOLATE_VERSION=$(date +%Y%m%d).$(git rev-parse HEAD) -v $PWD:/src deb:latest && mv *.deb titus-isolate_latest.deb
    artifact_paths: "*.deb"
  - wait
  - trigger: titus-upload-debs
    async: false
    branches: "master"
    build:
      env:
        CALLER_BUILD_ID: "${BUILDKITE_BUILD_ID}"
        CALLER_JOB_ID: "${BUILDKITE_JOB_ID}"
        CALLER_UPLOAD_DEB: "titus-isolate_latest.deb"
        CALLER_PACKAGE_NAME: "titus-isolate"
        BUILDKITE_CLEAN_CHECKOUT: "true"
