steps:
  - label: Build titus-isolate debian package
    command: ./build.sh
    artifact_paths: "*.deb"
    build:
      env:
        BUILDKITE_CLEAN_CHECKOUT: "true"
  - wait
  - trigger: titus-upload-debs
    async: false
    branches: "master"
    build:
      env:
        CALLER_BUILD_ID: "${BUILDKITE_BUILD_ID}"
        CALLER_JOB_ID: "${BUILDKITE_JOB_ID}"
        CALLER_UPLOAD_DEB: "titus-isolate_latest.deb"
        CALLER_PACKAGE_NAME: "titus-isolate"
        BUILDKITE_CLEAN_CHECKOUT: "true"
