# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import titus_isolate.allocate.remote.isolate_pb2 as isolate__pb2


class IsolationServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ComputeIsolation = channel.unary_unary(
                '/isolation.v1.IsolationService/ComputeIsolation',
                request_serializer=isolate__pb2.IsolationRequest.SerializeToString,
                response_deserializer=isolate__pb2.IsolationResponse.FromString,
                )
        self.GetCurrentCell = channel.unary_unary(
                '/isolation.v1.IsolationService/GetCurrentCell',
                request_serializer=isolate__pb2.CurrentCellRequest.SerializeToString,
                response_deserializer=isolate__pb2.CurrentCellResponse.FromString,
                )


class IsolationServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ComputeIsolation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCurrentCell(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_IsolationServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ComputeIsolation': grpc.unary_unary_rpc_method_handler(
                    servicer.ComputeIsolation,
                    request_deserializer=isolate__pb2.IsolationRequest.FromString,
                    response_serializer=isolate__pb2.IsolationResponse.SerializeToString,
            ),
            'GetCurrentCell': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCurrentCell,
                    request_deserializer=isolate__pb2.CurrentCellRequest.FromString,
                    response_serializer=isolate__pb2.CurrentCellResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'isolation.v1.IsolationService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class IsolationService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ComputeIsolation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/isolation.v1.IsolationService/ComputeIsolation',
            isolate__pb2.IsolationRequest.SerializeToString,
            isolate__pb2.IsolationResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetCurrentCell(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/isolation.v1.IsolationService/GetCurrentCell',
            isolate__pb2.CurrentCellRequest.SerializeToString,
            isolate__pb2.CurrentCellResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
