# Logs
LOG_FMT_STRING = '%(asctime)s,%(msecs)d %(levelname)s [%(filename)s:%(lineno)d] %(message)s'

# Metrics
DEFAULT_SAMPLE_FREQUENCY_SEC = 6

# Rebalance
REBALANCE_FREQUENCY_KEY = 'TITUS_ISOLATE_REBALANCE_FREQUENCY'
DEFAULT_REBALANCE_FREQUENCY = 60

# Reconcile
RECONCILE_FREQUENCY_KEY = 'TITUS_ISOLATE_RECONCILE_FREQUENCY'
DEFAULT_RECONCILE_FREQUENCY = 60

# Healthcheck
HEALTH_CHECK_FREQUENCY_KEY = 'TITUS_ISOLATE_HEALTHCHECK_FREQUENCY'
DEFAULT_HEALTH_CHECK_FREQUENCY = 60

MAX_TIME_SINCE_LAST_SUCCESSFUL_EVENT_KEY = 'TITUS_ISOLATE_MAX_TIME_SINCE_LAST_SUCCESSFUL_EVENT'
DEFAULT_MAX_TIME_SINCE_LAST_SUCCESSFUL_EVENT = 600  # Ten minutes

# Oversubscribe
OVERSUBSCRIBE_FREQUENCY_KEY = 'TITUS_ISOLATE_OVERSUBSCRIBE_FREQUENCY'
DEFAULT_OVERSUBSCRIBE_FREQUENCY = 60
OVERSUBSCRIBE_CLEANUP_AFTER_SECONDS_KEY = 'TITUS_ISOLATE_OVERSUBSCRIBE_CLEANUP_AFTER_SECONDS'
DEFAULT_OVERSUBSCRIBE_CLEANUP_AFTER_SECONDS = 1*60*60
OVERSUBSCRIBE_WINDOW_SIZE_MINUTES_KEY = 'TITUS_ISOLATE_OVERSUBSCRIBE_WINDOW_SIZE_MINUTES'
DEFAULT_OVERSUBSCRIBE_WINDOW_SIZE_MINUTES = 10
OVERSUBSCRIBE_BATCH_DURATION_PERCENTILE_KEY = 'TITUS_ISOLATE_OVERSUBSCRIBE_BATCH_DURATION_PERCENTILE'
DEFAULT_OVERSUBSCRIBE_BATCH_DURATION_PERCENTILE = 0.05

# CPU Allocator
CPU_ALLOCATOR = 'TITUS_ISOLATE_ALLOCATOR'
FALLBACK_ALLOCATOR = 'TITUS_ISOLATE_FALLBACK_ALLOCATOR'

# Remote Allocator
REMOTE_ALLOCATOR_URL = 'TITUS_ISOLATE_REMOTE_ALLOCATOR_URL'
REMOTE_ASSIGN_ALLOCATOR = 'REMOTE_ASSIGN_ALLOCATOR'
REMOTE_FREE_ALLOCATOR = 'REMOTE_FREE_ALLOCATOR'
REMOTE_REBALANCE_ALLOCATOR = 'REMOTE_REBALANCE_ALLOCATOR'

IP = 'IP'
FORECAST_CPU_IP = 'FORECAST_CPU_IP'
GREEDY = 'GREEDY'
NAIVE = 'NAIVE'
NOOP = 'NOOP'
REMOTE = 'REMOTE'
DEFAULT_ALLOCATOR = IP
DEFAULT_FALLBACK_ALLOCATOR = GREEDY
CPU_ALLOCATORS = [IP, FORECAST_CPU_IP, GREEDY, NAIVE, NOOP, REMOTE]

# Forecast CPU Allocator
ALPHA_NU = 'TITUS_ISOLATE_ALPHA_NU'
DEFAULT_ALPHA_NU = 1000.0

ALPHA_LLC = 'TITUS_ISOLATE_ALPHA_LLC'
DEFAULT_ALPHA_LLC = 10.0

ALPHA_L12 = 'TITUS_ISOLATE_ALPHA_L12'
DEFAULT_ALPHA_L12 = 250.0

ALPHA_ORDER = 'TITUS_ISOLATE_ALPHA_ORDER'
DEFAULT_ALPHA_ORDER = 1.0

ALPHA_PREV = 'TITUS_ISOLATE_ALPHA_PREV'
DEFAULT_ALPHA_PREV = 10.0

BURST_MULTIPLIER = 'TITUS_ISOLATE_BURST_MULTIPLIER'
DEFAULT_BURST_MULTIPLIER = 0.1

MAX_BURST_POOL_INCREASE_RATIO = 'TITUS_ISOLATE_MAX_BURST_POOL_INCREASE_RATIO'
DEFAULT_MAX_BURST_POOL_INCREASE_RATIO = 3.0

BURST_CORE_COLLOC_USAGE_THRESH = 'TITUS_ISOLATE_BURST_CORE_COLLOC_USAGE_THRESH'
DEFAULT_BURST_CORE_COLLOC_USAGE_THRESH = 0.2

WEIGHT_CPU_USE_BURST = 'TITUS_ISOLATE_WEIGHT_CPU_USE_BURST'
DEFAULT_WEIGHT_CPU_USE_BURST = 1.0

RELATIVE_MIP_GAP_STOP = 'TITUS_RELATIVE_MIP_GAP_STOP'
DEFAULT_RELATIVE_MIP_GAP_STOP = 0.05

MIP_SOLVER = 'TITUS_ISOLATE_MIP_SOLVER'
DEFAULT_MIP_SOLVER = 'GLPK_MI'

# Free Thread Provider
FREE_THREAD_PROVIDER = 'FREE_THREAD_PROVIDER'
EMPTY = 'EMPTY'
OVERSUBSCRIBE = 'OVERSUBSCRIBE'
DEFAULT_FREE_THREAD_PROVIDER = OVERSUBSCRIBE

# Threshold Free Thread Provider
TOTAL_THRESHOLD = 'TOTAL_THRESHOLD'
DEFAULT_TOTAL_THRESHOLD = 0.05

# NUMA balancing
TITUS_ISOLATE_DYNAMIC_NUMA_BALANCING = 'TITUS_ISOLATE_DYNAMIC_NUMA_BALANCING'
DEFAULT_TITUS_ISOLATE_DYNAMIC_NUMA_BALANCING = True

# Metrics querying
METRICS_QUERY_TIMEOUT_KEY = 'TITUS_ISOLATE_METRICS_QUERY_TIMEOUT_SEC'
DEFAULT_METRICS_QUERY_TIMEOUT_SEC = 5

# Event log
EVENT_LOG_FORMAT_STR = 'EVENT_LOG_FORMAT_STR'

# S3 Buckets
PROD = 'prod'
V1 = 'v1'
LATEST = 'latest'

MODEL_BUCKET_FORMAT_STR = 'TITUS_ISOLATE_MODEL_BUCKET_FORMAT_STR'
MODEL_PREFIX_FORMAT_STR = 'TITUS_ISOLATE_MODEL_PREFIX_FORMAT_STR'

MODEL_BUCKET_PREFIX = 'TITUS_ISOLATE_MODEL_BUCKET_PREFIX'
DEFAULT_MODEL_BUCKET_PREFIX = PROD

MODEL_BUCKET_LEAF = 'TITUS_ISOLATE_MODEL_BUCKET_LEAF'
DEFAULT_MODEL_BUCKET_LEAF = LATEST

# Kubernetes
GET_WORKLOAD_RETRY_COUNT = 'TITUS_ISOLATE_GET_WORKLOAD_RETRY_COUNT'
DEFAULT_GET_WORKLOAD_RETRY_COUNT = 3

GET_WORKLOAD_RETRY_INTERVAL_SEC = 'TITUS_ISOLATE_GET_WORKLOAD_RETRY_INTERVAL_SEC'
DEFAULT_GET_WORKLOAD_RETRY_INTERVAL_SEC = 1

# Static environment variables
PROPERTY_URL_ROOT = 'http://localhost:3002/properties'
EC2_INSTANCE_ID = "EC2_INSTANCE_ID"
EC2_LOCAL_IPV4 = "EC2_LOCAL_IPV4"

MAX_SOLVER_RUNTIME = 'TITUS_ISOLATE_MAX_SOLVER_RUNTIME'
DEFAULT_MAX_SOLVER_RUNTIME = 5

OPPORTUNISTIC_SHARES_SCALE_KEY = "OPPORTUNISTIC_SHARES_SCALE"
DEFAULT_SHARES_SCALE = 100
DEFAULT_OPPORTUNISTIC_SHARES_SCALE = DEFAULT_SHARES_SCALE

DEFAULT_QUOTA_SCALE = 100000

RESTART_PROPERTIES = [
    ALPHA_NU,
    ALPHA_LLC,
    ALPHA_L12,
    ALPHA_ORDER,
    ALPHA_PREV,
    BURST_CORE_COLLOC_USAGE_THRESH,
    BURST_MULTIPLIER,
    CPU_ALLOCATOR,
    FALLBACK_ALLOCATOR,
    FREE_THREAD_PROVIDER,
    MAX_BURST_POOL_INCREASE_RATIO,
    MAX_SOLVER_RUNTIME,
    METRICS_QUERY_TIMEOUT_KEY,
    MODEL_BUCKET_FORMAT_STR,
    MODEL_PREFIX_FORMAT_STR,
    OPPORTUNISTIC_SHARES_SCALE_KEY,
    REBALANCE_FREQUENCY_KEY,
    RECONCILE_FREQUENCY_KEY,
    REMOTE_ALLOCATOR_URL,
    TOTAL_THRESHOLD,
    WEIGHT_CPU_USE_BURST]
