ADDED_KEY = 'titus-isolate.added'
REMOVED_KEY = 'titus-isolate.removed'
SUCCEEDED_KEY = 'titus-isolate.succeeded'
FAILED_KEY = 'titus-isolate.failed'
ALLOCATOR_CALL_DURATION = 'titus-isolate.allocatorCallDurationSecs'
IP_ALLOCATOR_TIMEBOUND_COUNT = 'titus-isolate.ipAllocatorTimeBoundSolutionCount'
QUEUE_DEPTH_KEY = 'titus-isolate.queueDepth'
WORKLOAD_COUNT_KEY = 'titus-isolate.workloadCount'
EVENT_SUCCEEDED_KEY = 'titus-isolate.eventSucceeded'
EVENT_FAILED_KEY = 'titus-isolate.eventFailed'
EVENT_PROCESSED_KEY = 'titus-isolate.eventProcessed'
ADDED_TO_FULL_CPU_ERROR_KEY = 'titus-isolate.addedToFullCpu'

WRITE_CPUSET_SUCCEEDED_KEY = 'titus-isolate.writeCpusetSucceeded'
WRITE_CPUSET_FAILED_KEY = 'titus-isolate.writeCpusetFailed'
ISOLATED_WORKLOAD_COUNT = 'titus-isolate.isolatedWorkloadCount'

PACKAGE_VIOLATIONS_KEY = 'titus-isolate.crossPackageViolations'
CORE_VIOLATIONS_KEY = 'titus-isolate.sharedCoreViolations'

ALLOCATED_SIZE_KEY = 'titus-isolate.allocatedSize'
UNALLOCATED_SIZE_KEY = 'titus-isolate.unallocatedSize'
STATIC_ALLOCATED_SIZE_KEY = 'titus-isolate.staticAllocatedSize'
BURST_ALLOCATED_SIZE_KEY = 'titus-isolate.burstAllocatedSize'
BURST_REQUESTED_SIZE_KEY = 'titus-isolate.burstRequestedSize'
OVERSUBSCRIBED_THREADS_KEY = 'titus-isolate.oversubscribedThreads'

BURST_POOL_USAGE_KEY = 'titus-isolate.burstPoolUsage'

RUNNING = 'titus-isolate.running'
