ADDED_KEY = 'titus-isolate.addedCount'
REMOVED_KEY = 'titus-isolate.removedCount'
REBALANCED_KEY = 'titus-isolate.rebalancedCount'
SUCCEEDED_KEY = 'titus-isolate.succeededCount'
FAILED_KEY = 'titus-isolate.failedCount'
WORKLOAD_PROCESSING_DURATION = 'titus-isolate.workloadProcessingDurationSec'
UPDATE_STATE_DURATION = 'titus-isolate.updateStateDurationSec'
WORKLOAD_COUNT_KEY = 'titus-isolate.workloadCount'
EVENT_SUCCEEDED_KEY = 'titus-isolate.eventSucceeded'
EVENT_FAILED_KEY = 'titus-isolate.eventFailed'
EVENT_PROCESSED_KEY = 'titus-isolate.eventProcessed'

ENQUEUED_COUNT_KEY = 'titus-isolate.enqueuedCount'
DEQUEUED_COUNT_KEY = 'titus-isolate.dequeuedCount'
QUEUE_DEPTH_KEY = 'titus-isolate.queueDepth'
QUEUE_LATENCY_KEY = 'titus-isolate.queueLatency'
ISOLATE_LATENCY_KEY = 'titus-isolate.isolateLatency'
CONTAINER_BATCH_SIZE_KEY = 'titus-isolate.containerBatchSize'

WRITE_CPUSET_SUCCEEDED_KEY = 'titus-isolate.writeCpusetSucceeded'
WRITE_CPUSET_FAILED_KEY = 'titus-isolate.writeCpusetFailed'
ISOLATED_WORKLOAD_COUNT = 'titus-isolate.isolatedWorkloadCount'
CPUSET_THREAD_COUNT = 'titus-isolate.cpusetThreadCount'

PACKAGE_VIOLATIONS_KEY = 'titus-isolate.crossPackageViolations'
CORE_VIOLATIONS_KEY = 'titus-isolate.sharedCoreViolations'

EVENT_LOG_SUCCESS = 'titus-isolate.eventLogSuccessCount'
EVENT_LOG_RETRY = 'titus-isolate.eventLogRetryCount'
EVENT_LOG_FAILURE = 'titus-isolate.eventLogFailureCount'

ALLOCATED_SIZE_KEY = 'titus-isolate.allocatedSize'
UNALLOCATED_SIZE_KEY = 'titus-isolate.unallocatedSize'
OVERSUBSCRIBED_THREADS_KEY = 'titus-isolate.oversubscribedThreads'

PRIMARY_ASSIGN_COUNT = 'titus-isolate.assignThreadsPrimary'
PRIMARY_FREE_COUNT = 'titus-isolate.freeThreadsPrimary'
PRIMARY_REBALANCE_COUNT = 'titus-isolate.rebalancePrimary'
FALLBACK_ASSIGN_COUNT = 'titus-isolate.assignThreadsFallback'
FALLBACK_FREE_COUNT = 'titus-isolate.freeThreadsFallback'
FALLBACK_REBALANCE_COUNT = 'titus-isolate.rebalanceFallback'
FALLBACK_QUEUE_DEPTH_COUNT = 'titus-isolate.queueDepthFallback'

SOLVER_GET_CPU_ALLOCATOR_SUCCESS = 'titus-isolate.getCpuAllocatorSuccessCount'
SOLVER_GET_CPU_ALLOCATOR_FAILURE = 'titus-isolate.getCpuAllocatorFailureCount'
SOLVER_ASSIGN_THREADS_SUCCESS = 'titus-isolate.assignThreadsSuccessCount'
SOLVER_ASSIGN_THREADS_FAILURE = 'titus-isolate.assignThreadsFailureCount'
SOLVER_ASSIGN_THREADS_DURATION = 'titus-isolate.assignThreadsDurationSec'
SOLVER_FREE_THREADS_SUCCESS = 'titus-isolate.freeThreadsSuccessCount'
SOLVER_FREE_THREADS_FAILURE = 'titus-isolate.freeThreadsFailureCount'
SOLVER_FREE_THREADS_DURATION = 'titus-isolate.freeThreadsDurationSec'
SOLVER_REBALANCE_SUCCESS = 'titus-isolate.rebalanceSuccessCount'
SOLVER_REBALANCE_FAILURE = 'titus-isolate.rebalanceFailureCount'
SOLVER_REBALANCE_DURATION = 'titus-isolate.rebalanceThreadsDurationSec'

GET_RESOURCE_USAGE_FAILURE = 'titus-isolate.getResourceUsageFailureCount'

RUNNING = 'titus-isolate.running'

RECONCILE_SKIP_COUNT = 'titus-isolate.reconcileSkipCount'
RECONCILE_SUCCESS_COUNT = 'titus-isolate.reconcileSuccessCount'

PARSE_POD_REQUESTED_RESOURCES_FAIL_COUNT = 'titus-isolate.parsePodRequestedResourcesFailCount'
