WORKLOAD_JSON_FORMAT = '/var/lib/titus-environments/{}.json'
WORKLOAD_ENV_FORMAT = '/var/lib/titus-environments/{}.env'
WORKLOAD_ENV_LINE_REGEXP = r'(\w+)="([^"]*)"'

WORKLOAD_ENV_CPU_KEY = 'TITUS_NUM_CPU'
WORKLOAD_ENV_MEM_KEY = 'TITUS_NUM_MEM'
WORKLOAD_ENV_DISK_KEY = 'TITUS_NUM_DISK'
WORKLOAD_ENV_NETWORK_KEY = 'TITUS_NUM_NETWORK_BANDWIDTH'
WORKLOAD_ENV_WAIT_TIMEOUT_SECONDS = 10

WORKLOAD_JSON_APP_NAME_KEY = 'appName'
WORKLOAD_JSON_PASSTHROUGH_KEY = 'passthroughAttributes'
WORKLOAD_JSON_OWNER_KEY = 'titus.agent.ownerEmail'
WORKLOAD_JSON_IMAGE_KEY = 'fullyQualifiedImage'
WORKLOAD_JSON_IMAGE_DIGEST_KEY = 'imageDigest'
WORKLOAD_JSON_PROCESS_KEY = 'process'
WORKLOAD_JSON_COMMAND_KEY = 'command'
WORKLOAD_JSON_ENTRYPOINT_KEY = 'entrypoint'
WORKLOAD_JSON_JOB_TYPE_KEY = 'titus.agent.jobType'
WORKLOAD_JSON_CPU_BURST_KEY = 'allowCpuBursting'
WORKLOAD_JSON_OPPORTUNISTIC_CPU_KEY = 'task.opportunisticCpuCount'
WORKLOAD_JSON_WAIT_TIMEOUT_SECONDS = 10
WORKLOAD_JSON_READ_ATTEMPTS = 5
WORKLOAD_JSON_READ_SLEEP_SECONDS = 1
