ANNOTATION_KEY_INSTANCE_TYPE = 'node.titus.netflix.com/itype'
ANNOTATION_KEY_STACK = 'node.titus.netflix.com/stack'
ANNOTATION_KEY_CLUSTER = 'node.titus.netflix.com/cluster'
ANNOTATION_KEY_ASG = 'node.titus.netflix.com/asg'
LABEL_KEY_RESOURCE_POOL = 'scaler.titus.netflix.com/resource-pool'
LABEL_KEY_JOB_ID = 'v3.job.titus.netflix.com/job-id'
ANNOTATION_KEY_JOB_ID = 'titus.agent.jobId'
UNKNOWN_INSTANCE_TYPE = 'unknown'