WAIT_CGROUP_FILE_SEC_CHANGE_EXIT = 2
GENERIC_PROPERTY_CHANGE_EXIT = 3
RECONCILIATION_FAILURE_EXIT = 4
FAILURE_EXIT_CODE = 42
HEALTH_CHECK_EXCEPTION_EXIT_CODE = 43
HEALTH_CHECK_FAILURE_EXIT_CODE = 44

KUBERNETES_BACKEND_KEY = "KUBERNETES_BACKEND"
