WAIT_CGROUP_FILE_SEC_CHANGE_EXIT = 2
GENERIC_PROPERTY_CHANGE_EXIT = 3
RECONCILIATION_FAILURE_EXIT = 4
FAILURE_EXIT_CODE = 42
HEALTH_CHECK_EXCEPTION_EXIT_CODE = 43
HEALTH_CHECK_FAILURE_EXIT_CODE = 44
SCHEDULE_ONCE_FAILURE_EXIT_CODE = 45
SCHEDULING_LOOP_FAILURE_EXIT_CODE = 46
OPPORTUNISTIC_WATCH_FAILURE = 47

KUBERNETES_BACKEND_KEY = "KUBERNETES_BACKEND"
DEFAULT_KUBECONFIG_PATH = '/run/kubernetes/config'
